export const MAKI_ICONS_BASE_URL = "https://assets.plan4better.de/icons/maki";
export const MAKI_ICON_SIZE = 24; // px
export const NO_ICON_ICON = "hospital";
export const MAKI_ICON_TYPES = [
  {
    name: "Urban Infrastructure",
    icons: [
      "airfield",
      "airport",
      "bridge",
      "building-alt1",
      "building",
      "bus",
      "car-rental",
      "car-repair",
      "casino",
      "charging-station",
      "cinema",
      "communications-tower",
      "construction",
      "elevator",
      "entrance-alt1",
      "entrance",
      "fire-station-JP",
      "fire-station",
      "highway-rest-area",
      "historic",
      "home",
      "hospital-JP",
      "hospital",
      "industry",
      "lift-gate",
      "parking-garage",
      "parking-paid",
      "parking",
      "police-JP",
      "police",
      "post-JP",
      "post",
      "prison",
      "restaurant",
      "road-accident",
      "roadblock",
      "school-JP",
      "school",
      "shelter",
      "shop",
      "square-stroked",
      "square",
      "stadium",
      "teahouse",
      "telephone",
      "terminal",
      "theatre",
      "toll",
      "town-hall",
      "town",
      "tunnel",
      "village",
      "warehouse",
    ],
  },
  {
    name: "Recreation and Entertainment",
    icons: [
      "amusement-park",
      "aquarium",
      "baseball",
      "basketball",
      "bbq",
      "casino",
      "cinema",
      "gaming",
      "golf",
      "karaoke",
      "music",
      "park-alt1",
      "park",
      "picnic-site",
      "playground",
      "racetrack-boat",
      "racetrack-cycling",
      "racetrack-horse",
      "racetrack",
      "restaurant-bbq",
      "restaurant-noodle",
      "restaurant-pizza",
      "restaurant-seafood",
      "restaurant-sushi",
      "skiing",
      "soccer",
      "swimming",
      "table-tennis",
    ],
  },
  {
    name: "Nature and Environment",
    icons: [
      "beach",
      "farm",
      "garden-centre",
      "garden",
      "harbor",
      "hot-spring",
      "mountain",
      "natural",
      "park-alt1",
      "park",
      "viewpoint",
      "waterfall",
      "wetland",
      "windmill",
    ],
  },
  {
    name: "Health and Safety",
    icons: [
      "defibrillator",
      "drinking-water",
      "emergency-phone",
      "pharmacy",
      "veterinary",
      "waste-basket",
    ],
  },
  {
    name: "Cultural and Landmark",
    icons: [
      "art-gallery",
      "castle-JP",
      "castle",
      "landmark-JP",
      "landmark",
      "monument-JP",
      "monument",
      "museum",
      "place-of-worship",
      "marker",
      "marker-stroked",
      "foundation-marker",
    ],
  },
  {
    name: "Transportation and Vehicles",
    icons: [
      "aerialway",
      "bicycle-share",
      "bicycle",
      "bus",
      "car-rental",
      "car-repair",
      "ferry-JP",
      "ferry",
      "heliport",
      "rail-light",
      "rail-metro",
      "rail",
      "scooter",
      "slipway",
      "snowmobile",
    ],
  },
];
